### ISSUE TITLE
25 objets du quotidien qu'on peut éliminer

### ISSUE THREAD

**Issue by Naereen** [Naereen/Objectif-Zero-Dechet-2018#23]
> Voir cette vidéo:
> [![https://img.youtube.com/vi/M-7EHRFwsJU/0.jpg](https://img.youtube.com/vi/M-7EHRFwsJU/0.jpg)](https://www.youtube.com/watch?v=M-7EHRFwsJU)

## Réussites
- [x] :ok_man: Gel douche industriel / produit vaisselle → savon solide de Marseille (ça c'est déjà bon, cf. [cet article](https://perso.crans.org/besson/zero-dechet/bilan-dun-passage-a-marseille-chez-des-amies-30-06-2018.html#produits-dentretien-et-dhygiene) / produit vaisselle bio et en vrac
- [x] :ok_man: Essuie-tout jetable → torchon et serviette en tissu et en micro fibres
- [x] :ok_man: Cotons démaquillants jetables → cotons lavables (bon je me maquille pas… et j'ai un vieux paquet de cotons jetables qui devra durer des années pour les invitées donc… pas besoin)
- [x] :no_good_man: Film plastique et papier aluminium → tissu recouvert de cire d'abeille ? En fait, j'ai deux vieux vieux paquets des deux produits, j'en utilise *jamais* !
- [x] :no_good_man: Pailles en plastiques → en inox (j'utilise pas de paille… genre pas du tout depuis janvier ?)
- [x] :ok_man: Verres et couverts en plastiques → verres en verres (!) et couverts en inox (ça fait des années que j'ai mes couverts sur moi, et en conférence etc j'utilise soit un seul verre plusieurs jours soit un vrai contenant !)
- [x] :ok_man: Boîtes en plastique style Tupperware → boîtes en verre (OK j'ai encore mes boîtes en plastique mais j'utilise plus ma nouvelle boîte en verre ?)
- [x] :ok_man: Coton-tiges jetables → oriculi en bambou ou cure-oreille en inox (c'est bon !)
- [x] :no_good_woman: Tampons et serviettes : ça ne me concerne pas. Mais il y a des solutions plus écologiques (comme les "moon cups").
- [x] :ok_man: Briquet → allumettes (c'est bon, j'ai jamais acheté de briquet, je fais avec ceux que je trouve, et j'ai des allumettes)
- [x] :ok_man: Stylos jetables → rechargeables (c'est bon j'ai toujours écrit au stylo plume de toute ma vie !)
- [x] :ok_man: Bouteille en plastique jetable → gourde en verre ou en inox (c'est bon, j'ai une gourde Quechua de Decathlon, la même depuis des annnééées !)
- [x] :ok_man: Sacs en plastique → sacs en tissu ([tote bag](https://fr.wikipedia.org/wiki/Tote_bag)) (ça fait plus de 6 mois que je n'utilise plus que ça !)
- [x] :no_good_man: Mouchoirs jetables → mouchoirs en tissu (je crois je veux pas)
- [x] :no_good_man: Brosse à dent en plastique → en bambou recyclable ? Je vais devoir utiliser une brosse à dent électrique, donc tant pis pour cette initiative… Plus tard ?
- [x] :ok_man: Rasoirs jetables → rasoir de sûreté. ~~Ça je dois le faire, mais ça coûte cher et j'ai un (gros) stock de rasoirs (et je me rase beaucoup moins souvent !).~~ Donc… plus tard ! En 2021 : deux ans à se raser aux ciseaux, pas un seul rasoir acheté. Parfait !
- [x] Crème hydratante → huile naturelle ? ~~J'utilise qu'une seule crème et elle est bio, c'est déjà ça… mais pas assez d'utilisation crème pour vouloir essayer autre chose ?~~ En 2021 : aucune crème utilisée depuis 2019, parfait !
- [x] Éponge industrielle → éponge recyclable ou brosse (j'ai déjà une brosse en plastique… mais je m'en sers beaucoup plus que les éponges) #13. En 2021 : toujours la même brosse, increvable, parfait !
- [x] Déodorant toxique → déo solide bio fait maison #18 ou déo solide naturel (pierre d'Alun). En 2021 : la pierre d'Alun, plus d'autres astuces, mais pas acheté de déodorant industriel depuis 2019.

## Encore à essayer !
- [ ] Dentifrice industriel → dentifrice solide maison (j'ai essayé, je dois retenter !). En 2021 : il me reste deux dentifrices solides commerciaux (bio, locaux, savonnerie "Aubergine" près de Rennes), qui durent très longtemps.
- [ ] Shampoing industriel → shampoing solide maison #19. En 2021 : j'ai racheté une fois un gel douche et un shampoing commercial, pour les gens que j'accueille en CouchSurfing, je ne m'en sers pas. Il me reste deux shampoings solides de mes cadeaux de Noël 2019, je les utilise très lentement.
- [ ] Stick à lèvre → baume maison (à essayer !). En 2021 : j'ai quelques sticks à lèvre commerciaux, ils durent très longtemps, je n'en ai pas racheté depuis 2019 je pense. Bon j'ai peu voyagé en hiver ces deux derniers hivers, et encore moins fait de sports d'hiver, donc usure limitée...
- [ ] Lessive industrielle → lessive maison solide ? En 2021 : non mais j'achète de la lessive liquide bio en vrac au [Day by Day @ Rennes](https://daybyday-shop.com/magasin/rennes) et c'est vraiment très bien. Elle sent super bon, se conserve indéfiniment, n'est pas chère (~4.5€/L je crois, soit ~13€ pour ma grosse bouteille de 3L qui a duré plus d'un an en 2019/20/21).
